[window]
decorations = "None"
opacity = 1
blur = true
startup_mode = "Maximized"
padding = { x = 0, y = 0 }
dynamic_padding = true

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

#[font.italic]
#family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font]
size = 14
